-- cart-service schema: one cart per user, with restaurant-scoped line items.

CREATE TABLE carts (
    user_id       BIGINT      NOT NULL,
    restaurant_id BIGINT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_carts PRIMARY KEY (user_id)
);

CREATE TABLE cart_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cart_id          BIGINT NOT NULL,
    menu_item_id     BIGINT NOT NULL,
    name             VARCHAR(255) NOT NULL,
    qty              INTEGER NOT NULL,
    unit_price_cents BIGINT NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (user_id) ON DELETE CASCADE,
    CONSTRAINT chk_cart_items_qty CHECK (qty > 0),
    CONSTRAINT chk_cart_items_price CHECK (unit_price_cents >= 0)
);

CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
CREATE UNIQUE INDEX uq_cart_items_cart_menu ON cart_items (cart_id, menu_item_id);
