-- wallet-service schema: one wallet per user plus an append-only transaction ledger.

CREATE TABLE wallets (
    user_id       UUID         NOT NULL,
    balance_cents BIGINT       NOT NULL DEFAULT 0,
    currency      VARCHAR(3)   NOT NULL DEFAULT 'USD',
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_wallets PRIMARY KEY (user_id),
    CONSTRAINT chk_wallets_balance CHECK (balance_cents >= 0)
);

CREATE TABLE wallet_txns (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     UUID         NOT NULL,
    delta_cents BIGINT       NOT NULL,
    reason      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_wallet_txns PRIMARY KEY (id),
    CONSTRAINT fk_wallet_txns_wallet FOREIGN KEY (user_id) REFERENCES wallets (user_id) ON DELETE CASCADE
);

CREATE INDEX idx_wallet_txns_user_id ON wallet_txns (user_id);
CREATE INDEX idx_wallet_txns_created_at ON wallet_txns (created_at);
